# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 012a373d816010205e68068b17d8ebed56be659bf83303ecbe07b74897a6227a6149985dee4b2f6eef79d5fa32a0e4f5aaa0aff1f8be492ec60900704728014c

test:
  secret_key_base: c69daf8cf7538152c985dfb888d20fd5c8b8568c0cfbf17ac52ceaaf2c1d90d4e396342b138ffe86f21fe258f70411018a10464231312653ef9e7a50d405c767

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
